### PR TITLE
PIE-3214 - Update branch name from `master` to `trunk`

### PR DESCRIPTION
**Pull request by pandah3**
## Description

We are updating our branch names for this repo:

- `master` -> `trunk`

This PR updates all the references of the old name to the new one. Branch names will be changed in tandem when we merge the PR.

### CODE REVIEW

**Comment by pandah3** [comment]
I think we discussed leaving the `develop` branch name as is, but we may want to switch to `preprod` to align with the VIP Dashboard repo.

**Comment by andrea-sdl** [comment]
@pandah3 unless we are publishing a `-next` version on NPM I don't think having the `preprod` branch adds value over `develop` at the moment. If we move onto publishing also a `-next` version for people to test the VIP CLI then we can reconsider this option.

**Review by andrea-sdl — CHANGES_REQUESTED** [review]
@pandah3 should we also update the information in the `package.json` about the repo information with the new `vip-cli` url? [See here](https://github.com/Automattic/vip/blob/7ed412866e31e173fb5401fb19f6620505861979/package.json#L64-L64)

Aside from this little off-topic the PR is 👍

**Comment by pandah3** [comment]
> @pandah3 should we also update the information in the package.json about the repo information with the new vip-cli url? [See here](https://github.com/Automattic/vip/blob/7ed412866e31e173fb5401fb19f6620505861979/package.json#L64-L64)

Yes, added in [050c692](https://github.com/Automattic/vip-cli/pull/1109/commits/050c6925c601fce09ad5fb7434a51bda1ca32492)!

**Comment by mjangda** [comment]
I would like to get rid of the `develop` branch here and just have a single `trunk` branch. I don't see much of a benefit (feels like it just create unnecessary work right now) and will also get in the way of automating via GitHub Actions.

**Pull request closed without merging**
