### PR TITLE
Fix EPIPE error when hitting quit

### LINKED ISSUE #175: Quitting the display of an app list shows an error
Steps to reproduce:

1. `vip app list`
2. Type `q`

An error is displayed:

```
 ✕  Unexpected error: Please contact VIP Support with the following error:
  Error: write EPIPE
    at _errnoException (util.js:992:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:864:14)
```

### PR DESCRIPTION
**Pull request by elazzabi**
This error is raised when trying to write to a closed stream. Node doesn't get rid of those extra messages and raises an error as per https://github.com/nodejs/node/issues/947

From the same issue, it's supposed to be fixed in 8 and up. I tested in node 8 and 10 and I get the error.

This checks if the error code is `EPIPE` and return.

fixes #175

### CODE REVIEW

**Comment by elazzabi** [comment]
### Steps to test:
1. pull PR
2. run `npm link`
3. run `vip app list`
4. hit `q`
It should quit gracefully

**Comment by joshbetz** [comment]
Do we need to unpipe the pager when the main process exits?

**Comment by elazzabi** [comment]
@joshbetz not sure what do you mean

**Comment by joshbetz** [comment]
Sorry. If the issue is that we're trying to write to a closed stream, can we avoid writing to a closed stream by calling `.unpipe()` when the stream is closed?

**Comment by elazzabi** [comment]
I'm still not that familiar with how streams work in the code base, but I've added `.unpipe()` to places where I think it belongs (https://github.com/Automattic/vip/blob/master/src/lib/cli/pager.js#L29 and https://github.com/Automattic/vip/blob/master/src/lib/cli/pager.js#L35) but it looks like it doesn't resolve the problem

**Comment by joshbetz** [comment]
I think the problem is here:

https://github.com/Automattic/vip/blob/master/src/lib/cli/command.js#L326-L328

When this was originally added, I noted (#139):

```
This is a good start, but it would be better if we could page over
results and write 10 at a time. It would also be nice if that was
pausable (like stream.pause()) so we could lazy load results (or never
load results) that aren't going to be on screen anyway.
```

Ideally that would be a function that returns a stream of a CLI table and when we call stream.read() (which is what happens internally when you pipe a read stream to a write stream), it queries the next page of results from the API and formats the table.

Then, instead of manually calling `pager.write()` and `pager.end()`, we'd just pipe the results to the pager.

**Comment by elazzabi** [comment]
> ...it queries the next page of results from the API and formats the table.

I wonder if we are optimizing for ourselves instead of our users here. I think the average user don't have a list of more than few apps and we can afford getting them all in one request, don't you think so?

**Review by nickdaugherty — DISMISSED** [review]

**Pull request merged**
