### PR TITLE
Add sync preview

### LINKED ISSUE #164: Implement sync previews
Now that https://github.com/Automattic/vip-go-api-public/pull/163 is shipped, we can run a preview of sync before starting, to show accurate error messages and better confirmations.

Currently the error message when a config file on GitHub doesn't exist is "someone recently started sync", for example.

### PR DESCRIPTION
**Pull request by elazzabi**
This adds sync preview to the `vip sync` command.

### How to test?

1. clone the branch
2. run `npm link`
3. run `vip sync --app=XXX` where `XXX` is the id of an app
4. select the branch
5. verify if everything looks good
6. type N to abort sync

### Screenshot
screen shot 2018-10-24 at 9 32 02 am

fixes #164

### CODE REVIEW

**Comment by scottsweb** [comment]
Looks good to me:

screenshot-20181024094633-565x269

**Comment by scottsweb** [comment]
Only feedback I have from a visual stand point is that we should have the time in UTC to match the dashboard.

**Comment by elazzabi** [comment]
in the code it's `.toUTCString()` but in the output it's GMT... i guess it's the same 🤔

**Comment by scottsweb** [comment]
Oh yes it is. Sorry. I read that as local to me, but it is not. I am currently on BST. We switch to GMT soon though.

**Comment by mjangda** [comment]
@elazzabi I think you'll want to rebase with `master` to fix the tests.

**Review by mjangda — APPROVED** [review]
❤️

**Comment by elazzabi** [comment]
merged master but got this error in the appveyor build:

> EPERM: operation not permitted, scandir 'C:\projects\vip\node_modules\fsevents\node_modules'

Travis is good. ok to merge? cc @mjangda

**Comment by mjangda** [comment]
Yep, good to go.

**Pull request merged**
