### PR TITLE
Fix bug when comparing env data to selected environment

### PR DESCRIPTION
**Pull request by elazzabi**
## Description

We use the `getEnvironmentIdentifier` to identify environments but in this case, we were not comparing the unique identifier. Instead, we were comparing the env type only. This fixes it.

## Steps to Test

Outline the steps to test and verify the PR here.

Example:

The test cases can be found in BB8-7140

1. Run the test case in ^ and verify it's failing
1. Checkout this PR
1. Run `npm link`
1. Re-run the test case in ^ and verify it's fixed
2. Enjoy

### CODE REVIEW

**Review by chrean — APPROVED** [review]

**Comment by chrean** [comment]
@elazzabi when is this planned to be released?

**Comment by elazzabi** [comment]
@chrean well, I forgot to merge it, and now we need to release a new version 🤣

**Comment by elazzabi** [comment]
@chrean just noting that this was merged part of the `2.0.5` release

**Comment by chrean** [comment]
Thank you @elazzabi !

**Pull request merged**
