### PR TITLE
WP CLI - More comprehensive subshell cursor fix

### PR DESCRIPTION
**Pull request by nickdaugherty**
Resets the cursor at the beginning by sending a control code. This prevents instances where the cursor disappears, usually after `enquirer` prompts.

### CODE REVIEW

**Comment by nickdaugherty** [comment]
This needs testing on Windows

**Comment by nickdaugherty** [comment]
Tested and confirmed it works on Windows.

**Review by elazzabi — APPROVED** [review]
looks good :shipit:

**Comment by elazzabi** [comment]
Windows tests timing out as always, merging this

**Pull request merged**
