### PR TITLE
feat(dev-env): Pipe files to Docker instead of copying them when doing SQL import

### PR DESCRIPTION
**Pull request by sjinks**
## Description

`vip dev-env sql import` copies the SQL dump into the PHP container. This can be undesirable when the file is large: it creates unnecessary I/O, duplicates the file, and can potentially upset Docker if the copy operation exceeds the disk quota.

In this PR, we pipe the file to Docker instead.

## Steps to Test

Apply the patch and test all `vip dev-env sql import` scenarios.

### CODE REVIEW

**Comment by rinatkhaziev** [comment]
I think if we stream directly to MariaDB it should be even better because we'll be able to skip the intermediary PHP process

**Comment by sjinks** [comment]
True, but we don't know the MariaDB credentials in Lando.

**Comment by sjinks** [comment]
@rinatkhaziev OK, please take a look :-)

**Review by rinatkhaziev — APPROVED** [review]
Test on Mac and Windows, works great :)

**Pull request merged**
