### PR TITLE
SQL Import: Include completed ts, show failed on job step, & further clean up output

### PR DESCRIPTION
**Pull request by jblz**
## Description

* Print the "Completed" date now that it's present in the server response
* Indicate the Job step that failed
* Collect the "overall" status reporting at the bottom
* Further general tidying of the output

## Steps to Test

1. Check out PR.
1. Run `npm run build`
1. Run `./dist/bin/vip-import-sql.js` with various params
    * Verify the UX is improved
1. Repeat with `./dist/bin/vip-import-sql-status.js`
    * Verify the UX is improved

### CODE REVIEW

**Review by mjangda — APPROVED** [review]
Looks and works great!

**Comment by mjangda** [comment]
Screen Shot 2021-01-29 at 11 57 48 PM

**Comment by mjangda** [comment]
Actually, looks like we're repeatedly printing this:

```
=============================================================
Processing your sql import for env ID: 309, app ID: 309:
=============================================================
Processing your sql import for env ID: 309, app ID: 309:
=============================================================
Processing your sql import for env ID: 309, app ID: 309:
=============================================================
Processing your sql import for env ID: 309, app ID: 309:
=============================================================
Processing your sql import for env ID: 309, app ID: 309:
=============================================================
Processing your sql import for env ID: 309, app ID: 309:
=============================================================
Processing your sql import for env ID: 309, app ID: 309:
=============================================================
Processing your sql import for env ID: 309, app ID: 309:
=============================================================
Processing your sql import for env ID: 309, app ID: 309:
...
```

But overall, the new output including the `Complete` bit is great.

**Comment by jblz** [comment]
> Actually, looks like we're repeatedly printing this:
> 
> ```
> =============================================================
> Processing your sql import for env ID: 309, app ID: 309:
> ```

@mjangda  Hrm... I can't reproduce & don't see how that could happen (but I believe you of course!)  Any hints on how to reproduce?

if `DEBUG` is enabled, it can have unexpected results w/ the single log line output.

**Comment by jblz** [comment]
I'm going to go ahead and merge this & hopefully we'll get more eyes on the above issue.

**Comment by mjangda** [comment]
I think its a single-line-log bug. I've seen it happen in other CLIs as well where if the total lines of output is larger than the terminal window, you end up with this weird repeating behavior. You can probably reproduce if you increase your don't size. 

I don't think it's a blocker though.

**Comment by mjangda** [comment]
> I've seen it happen in other CLIs as well where if the total lines of output is larger than the terminal window, you end up with this weird repeating behavior. You can probably reproduce if you increase your don't size.

Yeah, if I decrease my font size, the problem doesn't happen. If I increase it, we see weird repeating bits (you may have to scroll up to see it).

Like I said, it's a bug in single-line-log. The quickest / easiest workaround is to cut down the number of lines we're outputting (but that's just a cat-and-mouse style game :))

**Comment by jblz** [comment]
"fun" :)

**Pull request merged**
