### PR TITLE
Remove help and version in favor of -h/--help and -v/--version

### LINKED ISSUE #162: Help for subcommands
Currently when you pass the `-h` param, you get the help for all top level commands, not specific help for a subcommand:

```
$ vip -h
  Usage: vip [options] [command]

  Commands:
    app      List and modify your VIP Go apps
    help     Display help
    logout   Logout from your current session
    sync     Sync production to a development environment
    version  Display version

  Options:
    -h, --help     Output usage information
    -v, --version  Output the version number

$ vip app -h
  Usage: vip [options] [command]

  Commands:
    app      List and modify your VIP Go apps
    help     Display help
    logout   Logout from your current session
    sync     Sync production to a development environment
    version  Display version

  Options:
    -h, --help     Output usage information
    -v, --version  Output the version number
```

### PR DESCRIPTION
**Pull request by elazzabi**
_This is a PR to see how the help and version will look like if we remove `help`/`version` and replace it with `-h`/`-v` and `--help`/`--version` flags instead._

This will make the help displays only if `-h` or `--help` are passed, which is the correct behavior. Before this, in order for the help to be shown, you need `-h`, `--help` or `help` but that causes some problems with subcommands see #162.

This fix #162 and #293 

### How to test:

1. Get current branch
2. Run `npm link`
3. Run `vip -h` you should get the help for vip
4. Run `vip app -h` or any subcommand, you should get the help for that subcommand

### CODE REVIEW

**Review by nickdaugherty — COMMENTED** [review]
I personally like this a lot more, and it feels more consistent with other CLI tools I'm used to, besides WP CLI which is backwards anyway (`wp help post`).

Question - where does `(disabled by default)` come from in the help, and can we remove it?

```
$ ./dist/bin/vip.js -h
...
  Options:
    -h, --help     Output the help for the (sub)command (disabled by default)
    -v, --version  Output the version number (disabled by default)
```

**Comment by nickdaugherty** [comment]
Also ping @mjangda and @joshbetz for thoughts as this changes existing behavior.

**Comment by elazzabi** [comment]
@nickdaugherty looks like it was caused by the `false` being used when declaring the options. Fixed by this https://github.com/Automattic/vip/pull/295/commits/e696304ef06058d2dcfde78f48400d8b48a83b43

**Comment by joshbetz** [comment]
Agree, this looks good to me.

**Review by nickdaugherty — APPROVED** [review]
🚢

**Comment by elazzabi** [comment]
Tests are passing but timing out, merging

**Pull request merged**
