### PR TITLE
Include options into reading software config

### PR DESCRIPTION
**Pull request by pschoffer**
## Description

For scripting purposes it might be useful to be able to see what versions of given software stack are available. 

This change adds `--include options` switch that does just that.

## Steps to Test

```
npm run build && ./dist/bin/vip-config-software-get.js @2891 --include options --format json
[
        {
                "name": "WordPress",
                "slug": "wordpress",
                "version": "6.0 (managed updates)",
                "options": [
                        "managed_latest",
                        "6.0",
                        "5.9",
                        "trunk",
                        "5.8",
                        "5.7"
                ]
        },
        {
                "name": "PHP",
                "slug": "php",
                "version": "8.1",
                "options": [
                        "8.1",
                        "8.0",
                        "7.4"
                ]
        },
        {
                "name": "MU Plugins",
                "slug": "muplugins",
                "version": "staging",
                "options": [
                        "production",
                        "staging"
                ]
        }
]


npm run build && ./dist/bin/vip-config-software-get.js @2891 --include options
┌────────────┬───────────┬───────────────────────┬──────────────────────────────────────┐
│ name       │ slug      │ version               │ options                              │
├────────────┼───────────┼───────────────────────┼──────────────────────────────────────┤
│ WordPress  │ wordpress │ 6.0 (managed updates) │ managed_latest,6.0,5.9,trunk,5.8,5.7 │
├────────────┼───────────┼───────────────────────┼──────────────────────────────────────┤
│ PHP        │ php       │ 8.1                   │ 8.1,8.0,7.4                          │
├────────────┼───────────┼───────────────────────┼──────────────────────────────────────┤
│ MU Plugins │ muplugins │ staging               │ production,staging                   │
└────────────┴───────────┴───────────────────────┴──────────────────────────────────────┘
```

### CODE REVIEW

**Comment by mjangda** [comment]
`options` doesn't sound or feel right to me for some reason. I think it's because it's just a bit generic. Is this what we call it in the API as well? Are there other CLI tools or APIs we can use as a reference to see what terminology they use?

**Comment by pschoffer** [comment]
Yeah I took it from the API response directly. Would switching to `Valid options` help? I little harder on scripting with the space there though.

@WPprodigy would you have an idea on the naming?

**Comment by WPprodigy** [comment]
I'm not sure. "options" seems okay to me, as this is a list of available options/choices that can be selected from.

**Comment by rebeccahum** [comment]
What about `available_versions`?

**Comment by mjangda** [comment]
I like `available_versions` 👍 🚢

**Comment by pschoffer** [comment]
Renamed. Thanks for the patience :)

**Review by jesse-greathouse — APPROVED** [review]
👍  nice work!

**Pull request merged**
