### PR TITLE
Add error message for rate limit

### LINKED ISSUE #283: Handle rate limit better
Currently when a user send a batch of more than 2 commands, an error like this raises:

```
✕  Unexpected error: Please contact VIP Support with the following error:
  Error: Unhandled "error" event. (Rate limit exceeded)
    at Socket.emit (events.js:186:19)
    at Socket.<anonymous> (/usr/local/lib/node_modules/@automattic/vip/node_modules/component-bind/index.js:21:15)
    at Socket.Emitter.emit (/usr/local/lib/node_modules/@automattic/vip/node_modules/component-emitter/index.js:133:20)
    at Socket.emit (/usr/local/lib/node_modules/@automattic/vip/node_modules/socket.io-client/lib/socket.js:138:10)
    at Socket.onpacket (/usr/local/lib/node_modules/@automattic/vip/node_modules/socket.io-client/lib/socket.js:256:12)
    at Manager.<anonymous> (/usr/local/lib/node_modules/@automattic/vip/node_modules/component-bind/index.js:21:15)
    at Manager.Emitter.emit (/usr/local/lib/node_modules/@automattic/vi....
```
We need to catch those errors and display a better message

### PR DESCRIPTION
**Pull request by elazzabi**
This handles the rate limit error and displays an error message:

`Error: you can not run more than two commands in the same time against an environment.`

Ideally we should check for the `code` of the error object instead of the message, but looks like the error received isn't an object, it's a string containing the error message :/

### Testing
1. Get this branch
2. Run `npm link`
3. Enter the subshell mode for an environment
4. Paste the following
```
wp option get home
wp option get home
wp option get home
```
5. You should see the error message
6. Try with two only
```
wp option get home
wp option get home
```
7. Should work

fix #283

### CODE REVIEW

**Comment by simonwheatley** [comment]
Where does "two" come from? What happens if an application has more or less than two CLI containers?

**Comment by elazzabi** [comment]
@simonwheatley currently, every site has one container that can run 2 commands at the same time. But if we have more than one, that error message isn't valid anymore, my bad. Thank you for spotting this.

Any idea how we can phrase this ^?

**Comment by nickdaugherty** [comment]
> Any idea how we can phrase this

How about - "Maximum concurrent running commands have been reached, please allow some to finish before starting another."

**Comment by simonwheatley** [comment]
Let's go with @nickdaugherty's suggestion 👍

**Comment by nickdaugherty** [comment]
This "rate limit" error is actually unrelated to the maximum number of concurrent commands allowed - it's a rate limit in Parker designed to prevent abuse, so the wording I suggested is actually wrong. It needs to be something like:

"Rate limit exceeded: Please wait a moment and try again".

Aside - is there a way we can prevent copy/pasting a big bunch of commands? Ideally the subshell only allows 1 to be triggered at a time.

**Comment by elazzabi** [comment]
> This "rate limit" error is actually unrelated to the maximum number of concurrent commands allowed - it's a rate limit in Parker designed to prevent abuse, so the wording I suggested is actually wrong. It needs to be something like:
> 
> "Rate limit exceeded: Please wait a moment and try again".
> 
> Aside - is there a way we can prevent copy/pasting a big bunch of commands? Ideally the subshell only allows 1 to be triggered at a time.

I updated the message accordingly. I guess the `line` event is raised whenever a new line is submitted. Not sure if we can block this with some config in `readline` but we can hack it using a global var or something. We can look at this in the future I think.

**Review by nickdaugherty — APPROVED** [review]

**Pull request merged**
