### PR TITLE
await tracking events

### PR DESCRIPTION
**Pull request by elazzabi**
## Description

We used the fire and forget approach for those tracking events. However, some aren't recorded as the process is already closed with no time to send the events

### CODE REVIEW

**Comment by joshbetz** [comment]
Minor, but what if we await them at the end? This could look like:

```javascript
const tracksEvents = [];

// Do some stuff

tracksEvents.push( trackEvent( 'wpcli_command_execute', commonTrackingParams ) );

// Do some other stuff

await Promise.all( tracksEvents );
```

The advantage here is that we don't wait for them unless we need to.

**Comment by elazzabi** [comment]
@joshbetz When I added this, my thinking was: lets `await` only the events that needs to be awaited, ie those appearing just before the closing of the process: `command_cancel` and `command_end`. For others, they still have time to report, so they aren't awaited, fired and forget about.

What do you think? 🤔

**Comment by joshbetz** [comment]
@elazzabi probably fine for now and definitely simpler to implement. If we notice problems in the future, we can do what I've suggested.

**Review by joshbetz — DISMISSED** [review]

**Comment by elazzabi** [comment]
Thank you for the review Josh. This branch was behind master and had some merging conflicts. Merging now

**Pull request merged**
