### PR TITLE
Remove app context graphql request

### PR DESCRIPTION
**Pull request by elazzabi**
The removed graphql request get executed whenever a user runs a command without an app context (ie without a `--app` flag) which makes the command line freeze until we get a list of apps (first 100) the user can choose from.

This PR bypass this behavior by asking the user to give the `id` or `slug` of the app then making a call to the api with that information.

This resolves that freezing time, but now we don't show a list to choose from. We should think of a better way of doing it in the first place (probably by getting a list of apps and caching them locally) instead of calling it each time a command is executed without the `app` flag.

_`enquirer` is scheduled to replace `inquirer` and have an `autocomplete` feature we can use in this case with a cached list_

### CODE REVIEW

**Comment by nickdaugherty** [comment]
Do you have an example of what commands trigger this? I'm just wondering how much overhead it's adding in practice - aren't most commands using an `--app` option?

Also, for speed, maybe we just lower the page size? I worry that changing existing behavior could cause confusion for existing users, when this optimization seems to mostly impact us (who have lots of apps to choose from).

**Comment by elazzabi** [comment]
Any command that accepts an `--app` flag will run this query (ex, `sync`, `app`). In fact, the idea behind it was that if the user didn't provide an app, try getting a list and ask him to chose one from it.

As you said, most clients will automate things and run commands with the `--app` flag. If not, we ask them to chose an app with a prompt now (other than the list we were using before).

I think it's a good idea and we definitely need to implement it, but differently. For ex:
+ Get all apps and cache the results (for some time) instead of firing that query every time a command is run
+ With `enquirer` we'll have autocomplete feature we can use instead of a list of apps to chose from

**Comment by nickdaugherty** [comment]
cc @joshbetz for thoughts on this PR

**Comment by joshbetz** [comment]
How much of a problem is this for us vs everyone else? I suspect that when you only have a few apps, this query is pretty fast.

That said, I think a better way forward would be to cache the query instead of removing it. IMO, we should never be in the situation where you have to lookup and copy/paste the name of your app in order for these commands to be useful.

**Comment by joshbetz** [comment]
> As you said, most clients will automate things and run commands with the `--app` flag. 

This might be true, but I think the CLI should still be usable for humans. It's nice that this offers a way to automate processes on VIP Go, but I'd say the user experience is still important.

**Comment by elazzabi** [comment]
If we merge this PR, it does not mean we are going to ship it to clients unless we ship a new version explicitly. Maybe I expressed myself wrongly, but the idea was never to remove it completely. I removed it in this PR in order to speed other things (especially replacing `inquirer` with `enquirer`) and I was planning to re-implement it with autocompletion and caching as I said ^

Closing this

**Pull request closed without merging**
